library(dplyr)
library(reshape2)
library(stringr)
library(usmap)
library(ggplot2)
library(data.table)
library(lubridate)
selected<-select(farmers_market_info,State,Organic,Bakedgoods,Cheese,Crafts,Flowers,Eggs,Seafood,Herbs,Vegetables,Honey,Jams,Maple,Meat,Nursery,Nuts,Plants,Poultry,Prepared,Soap,Trees,Wine,Coffee,Beans,Fruits,Grains,Juices,Mushrooms,PetFood,Tofu,WildHarvested,Season1Date,Credit, WIC, WICcash,SNAP, SFMNP)
selected$Organic<-ifelse(selected$Organic =='Y', 1,0)
selected$Bakedgoods<-ifelse(selected$Bakedgoods =='Y', 1,0)
selected$Cheese<-ifelse(selected$Cheese =='Y', 1,0)
selected$Crafts<-ifelse(selected$Crafts =='Y', 1,0)
selected$Flowers<-ifelse(selected$Flowers =='Y', 1,0)
selected$Eggs<-ifelse(selected$Eggs =='Y', 1,0)
selected$Seafood<-ifelse(selected$Seafood =='Y', 1,0)
selected$Herbs<-ifelse(selected$Herbs =='Y', 1,0)
selected$Vegetables<-ifelse(selected$Vegetables =='Y', 1,0)
selected$Honey<-ifelse(selected$Honey =='Y', 1,0)
selected$Jams<-ifelse(selected$Jams =='Y', 1,0)
selected$Maple<-ifelse(selected$Maple =='Y', 1,0)
selected$Meat<-ifelse(selected$Meat =='Y', 1,0)
selected$Nursery<-ifelse(selected$Nursery =='Y', 1,0)
selected$Nuts<-ifelse(selected$Nuts =='Y', 1,0)
selected$Plants<-ifelse(selected$Plants =='Y', 1,0)
selected$Poultry<-ifelse(selected$Poultry =='Y', 1,0)
selected$Prepared<-ifelse(selected$Prepared =='Y', 1,0)
selected$Soap=ifelse(selected$Soap =='Y', 1,0)
selected$Trees=ifelse(selected$Trees =='Y', 1,0)
selected$Wine=ifelse(selected$Wine =='Y', 1,0)
selected$Coffee=ifelse(selected$Coffee =='Y', 1,0)
selected$Beans=ifelse(selected$Beans =='Y', 1,0)
selected$Fruits=ifelse(selected$Fruits =='Y', 1,0)
selected$Grains=ifelse(selected$Grains =='Y', 1,0)
selected$Juices=ifelse(selected$Juices =='Y', 1,0)
selected$Mushrooms=ifelse(selected$Mushrooms =='Y', 1,0)
selected$PetFood=ifelse(selected$PetFood =='Y', 1,0)
selected$Tofu=ifelse(selected$Tofu =='Y', 1,0)
selected$WildHarvested=ifelse(selected$WildHarvested =='Y', 1,0)
selected$SFMNP=ifelse(selected$SFMNP =='Y', 1,0)
selected$SNAP=ifelse(selected$SNAP =='Y', 1,0)
selected$WICcash=ifelse(selected$WICcash =='Y', 1,0)
selected$WIC=ifelse(selected$WIC =='Y', 1,0)
selected$Credit=ifelse(selected$Credit =='Y', 1,0)
selected[is.na(selected)] <- 0
season2<-selected 
season2$Season1Date<-gsub('January','0',season2$Season1Date)
season2$Season1Date<-gsub('February','0',season2$Season1Date)
season2$Season1Date<-gsub('March','0',season2$Season1Date)
season2$Season1Date<-gsub('April','0',season2$Season1Date)
season2$Season1Date<-gsub('May','0',season2$Season1Date)
season2$Season1Date<-gsub('June','0',season2$Season1Date)
season2$Season1Date<-gsub('July','0',season2$Season1Date)
season2$Season1Date<-gsub('August','0',season2$Season1Date)
season2$Season1Date<-gsub('September','0',season2$Season1Date)
season2$Season1Date<-gsub('October','0',season2$Season1Date)
season2$Season1Date<-gsub('November','0',season2$Season1Date)
season2$Season1Date<-gsub('December','0',season2$Season1Date)
newColNames <- c("start", "end")
newCols <- colsplit(season2$Season1Date, "to", newColNames)
newCols$end<-NULL
newCols$start=format(as.Date(newCols$start, format = "%m/%d/%Y"),"%Y")
new<-cbind(newCols,season2)
new$Season1Date<-NULL

omitna<-na.omit(new)
selects<-select(omitna,State,start,Organic,Bakedgoods,Cheese,Crafts,Flowers,Eggs,Seafood,Herbs,Vegetables,Honey,Jams,Maple,Meat,Nursery,Nuts,Plants,Poultry,Prepared,Soap,Trees,Wine,Coffee,Beans,Fruits,Grains,Juices,Mushrooms,PetFood,Tofu,WildHarvested,WICcash,SFMNP,Credit,SNAP,WIC)
passing_val<-c("State","start","WICcash","SFMNP","Credit","SNAP","WIC")
passing_names<-c("Organic","Bakedgoods","Cheese","Crafts","Flowers","Eggs","Seafood","Herbs","Vegetables","Honey","Jams","Maple","Meat","Nursery","Nuts","Plants","Poultry","Prepared","Soap","Trees","Wine","Coffee","Beans","Fruits","Grains","Juices","Mushrooms","PetFood","Tofu","WildHarvested")
melt_value=melt(selects,id.vars=passing_val,measure.vars=passing_names)
x<-filter(melt_value,value>0)
passing_val1<-c("State","start","variable")
passing_names1<-c("WICcash","SFMNP","SNAP","Credit","WIC")
melt_value1<-melt(x,id.vars=passing_val1,measure.vars=passing_names1)
names(melt_value1)[3]<-"Product_Type"
names(melt_value1)[4]<-"Payment_Mode"
names(melt_value1)[2]<-"Year"

final<-filter(melt_value1,value>0)
pl<-summarise(group_by(final,State,Year,Product_Type,Payment_Mode),count=sum(value))
library(zoo)
pl$Year<-as.Date(pl$Year,format="%Y")
pl$Year=format(as.Date(pl$Year, format = "%Y-%m-%d"),"%Y")
m<-merge(pl,ABBS,by.x="State",by.y="State")


