---
title: "assignment 3"
output: html_document
---
```{r}
#packages
library(dplyr)
library(ggplot2)
library(magrittr)
library(reshape)
```
```{r}
#Question 1
l <- airline_delay %>%
  group_by(carrier_name) %>%
  summarise(total_arrival_delay = sum(arr_delay,na.rm=TRUE))
arrange(l,total_arrival_delay) #gives the sum of total arrival delays for each airline
l$carrier_name = factor(l$carrier_name,levels=l$carrier_name[order(l$total_arrival_delay)]) #used to arrange in ascending order

ggplot(data = l,aes(y = total_arrival_delay, x = carrier_name)) + 
  geom_bar(stat = "identity") + 
  coord_flip() +
  xlab("Carrier name") + ylab("Total Arrival Delay") #Used to plot the table as a bar graph
```

```{r}
#Question 2
l <- airline_delay %>%
  group_by(carrier_name,year) %>%
  summarise(total_arrival_delay = sum(arr_delay,na.rm=TRUE))
arrange(l,total_arrival_delay)
ggplot(l,aes(x = reorder(carrier_name,total_arrival_delay),y = total_arrival_delay,fill=factor(year))) + geom_bar(stat = "identity") + coord_flip() + theme() + xlab("Carrier name") + ylab("Total Arrival Delay")#used to plot the table in a stacked bar graph
```

```{r}
#Question 3
t = select(airline_delay,airport,arr_delay,year) #selects only the mentioned columns from the dataset
df1 <- filter(t,airport=="SFO"|airport=="ORD"|airport=="LGA"|airport=="LAX"|airport=="JFK"|airport=="EWR"|airport=="DFW"|airport=="DEN"|airport=="BOS"|airport=="ATL") #filters the airports from t and takes out only the ones we want
f <- summarise(group_by(df1,airport,year), arrival_delay=sum(arr_delay)) #adds arrival delay based on aiport and year
f%>%
ggplot(mapping=aes(x = year, y = airport))+
  geom_tile(mapping=aes(fill = arrival_delay)) + xlab("Year") + ylab("Airport Name") + labs(fill="Total Arrival Delay")#tile function is used to plot heat maps
```

```{r warning=TRUE}
#Question 4
temp2 = select(airline_delay,year,carrier_delay,late_aircraft_delay) #selects the required columns from the dataset
melted = melt(temp2,id = "year") #takes year as an id and gives the value of each carrier delay and late aircraft delay
x1 <- na.omit(melted) #removes NA
f3 <- summarise(group_by(x1,year,variable),mins = sum(value))
names(f3)[2] <- "Delay_Type"
ggplot(data = f3,aes(x = year,y = mins, color = Delay_Type)) + geom_line() + xlab("Year") + ylab("Mins") #line function is used for a line plot

```


```{r}
#Question 5
temp=select(airline_delay,airport,arr_delay) 
df2 <- filter(temp,airport=="ATL"|airport=="BOS"|airport=="JFK")
#Box Plot
ggplot(df2, aes(x = airport, y = arr_delay)) + 
  geom_boxplot(outlier.size = 0.6) + xlab("Airport") + ylab("Arrival Delay in Mins")
#Violin Plot
ggplot(df2, aes(x = airport, y = arr_delay)) + 
  geom_violin() + xlab("Airport") + ylab("Arrival Delay in Mins")
#Density Plot
ggplot(df2, aes(x = arr_delay, fill = airport)) + geom_density(alpha = 0.5,lwd = 0.3) + xlab("Arrival Delay(Mins)")
```

```{r}
#Question 6
#part 1
mergetable <-merge(airline_delay,enplanement1,by.x = "airport",by.y = "Locid")
newtable <- select(mergetable,airport,CY.17.Enplanements,arr_delay)
x <- na.omit(newtable) #used to omit rows with NA
x$CY.17.Enplanements = as.integer(as.factor("x$CY.17.Enplanements")) #Enplanements is in character, so converting it to an integer
#part 2
grouped = summarise(group_by(x,airport), Enplanements = sum(CY.17.Enplanements), Arrival_delay = sum(arr_delay))
#part 3
ggplot(grouped,aes(x = Enplanements,y = Arrival_delay)) + geom_point()
#part 4
ggplot(grouped,aes(x = Enplanements,y = Arrival_delay)) + geom_point() + scale_x_continuous(trans = 'log10') + scale_y_continuous(trans = 'log10') #scale_x is used to convert to log values
```





